version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  vfcommon: voiceflow/common@0.0.13

jobs:
  build-and-test:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - run:
          name: 'Build package'
          command: |
            yarn build
      - run:
          name: 'Run tests'
          command: |
            yarn test
      - codecov/upload:
          file: nyc_coverage/lcov.info

workflows:
  test-and-release:
    jobs:
      - build-and-test
      - vfcommon/release:
          requires:
            - build-and-test
          filters:
            branches:
              only: master

